config/routes.rb
Rails.application.routes.draw do
  get '/team', to: 'static#team'
  get '/contact', to: 'static#contact'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'welcome/:first_name', to: 'welcome#show'
  root 'gossips#index'
  get '/', to: 'gossips#index'
  get 'gossips/:gossip_index', to: 'gossips#show', as: 'gossip'
  get 'users/:user_index', to: 'users#show', as: 'user'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :gossip
  belongs_to :author, class_name: "User"
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :author, class_name: "User"
  has_many :comments
  has_many :join_table_tag_gossips, foreign_key: :gossip_id, class_name: "JoinTableTagGossip"
  has_many :tags, through: :join_table_tag_gossips
end

app/models/join_table_recipient_pm.rb
class JoinTableRecipientPm < ApplicationRecord
  belongs_to :private_message
  belongs_to :recipient, class_name: "User"
end

app/models/join_table_tag_gossip.rb
class JoinTableTagGossip < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  has_many :join_table_recipient_pms, foreign_key: :private_message_id, class_name: "JoinTableRecipientPm"
  has_many :recipients, through: :join_table_recipient_pms
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :join_table_tag_gossips, foreign_key: :tag_id, class_name: "JoinTableTagGossip"
  has_many :gossips, through: :join_table_tag_gossips
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_many :gossips, foreign_key: 'author_id', class_name: "Gossip"
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :join_table_recipient_pms, foreign_key: :recipient_id, class_name: "JoinTableRecipientPm"
  has_many :received_messages, through: :join_table_recipient_pms
  has_many :comments, foreign_key: 'author_id', class_name: "Comment"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  def index
    @gossips = Gossip.all
    puts "$" * 60
    puts "Voici le nombre de potins dans la base : #{@gossips.length}"
    puts "$" * 60
  end

  def show
    @gossip_hash = { "gossip" => nil, "index" => -1 }
    gossip_id = params[:gossip_index].to_i
    puts "$" * 60
    puts "gossip_id : #{gossip_id}"
    if (gossip_id != -1)
      gossip = Gossip.find(gossip_id)
      puts "gossip : #{gossip}"
      @gossip_hash = { "gossip" => gossip, "index" => gossip_id }
      puts "gossip_hash : #{@gossip_hash}"
    end
    puts "$" * 60
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def team
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    puts "$" * 60
    puts "Voici le nombre d'utilisateurs dans la base : #{@users.length}"
    puts "$" * 60
  end

  def show
    @user_hash = { "user" => nil, "index" => -1 }
    user_id = params[:user_index].to_i
    puts "$" * 60
    puts "user_id : #{user_id}"
    if (user_id != -1)
      user = User.find(user_id)
      puts "user : #{user}"
      @user_hash = { "user" => user, "index" => user_id }
      puts "user_hash : #{@user_hash}"
    end
    puts "$" * 60
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def show
    puts "$" * 60
    puts "Voici le prénom que l'utilisateur a saisi dans l'URL :"
    puts params[:first_name]
    puts "$" * 60
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/gossips/index.html.erb
<style type="text/css">
  table {
    margin:auto;
  }
  table,
  td {
    border: 1px solid #333;
  }

  thead,
  tfoot {
    background-color: #333;
    color: #fff;
  }
</style>

<div>
  <h1>Bienvenue sur l'application de la communauté de <em>"The Hacking Project"</em></h1>
  <table>
    <caption>Voici la liste des potins qui circulent...</caption>
    <thead>
      <tr>
        <th>Prénom de l'auteur</th>
        <th>Titre</th>
        <th>Page</th>
      </tr>
    </thead>
    <tbody>
      <% @gossips.each do |gossip| %>
        <tr>
          <td><%= gossip.author.first_name %></td>
          <td><%= gossip.title %></td>
          <td><%= link_to "Potin n°#{gossip.id}", gossip_path(gossip.id) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/gossips/show.html.erb
<style type="text/css">
  .content {
    font-style: italic;
    border-radius: 10px !important;
    text-indent: 12px !important;
    width: auto !important;
    padding: 0px 8px !important;
    text-align: center !important;
    vertical-align: middle !important;
    font: bold 11px / 20px &quot;Helvetica Neue&quot;, Helvetica, sans-serif !important;
    --color: rgb(255, 255, 255) !important;
    }
</style>

<h1>Voici la page du potin n°<%= @gossip_hash['index'] %></h1>
<div>
  <% if !@gossip_hash['gossip'].nil? %>
    <p class="author">Son auteur : <em><%= link_to "#{@gossip_hash['gossip'].author.first_name} #{@gossip_hash['gossip'].author.last_name}", user_path(@gossip_hash['gossip'].author.id) %></em></p>
    <p>Son titre : <%= @gossip_hash['gossip'].title %></p>
    <p>Le contenu du potin : <p class="content"><%= @gossip_hash['gossip'].content %></p></p>
    <p>La date de création du potin : <%= @gossip_hash['gossip'].created_at %></p>
  <% else %>
    <p>Aucun potin de n°<%= @gossip_hash['index'] %> n'existe dans la base!</p>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Gossip Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootswatch@4.5.2/dist/cosmo/bootstrap.min.css" integrity="sha384-5QFXyVb+lrCzdN228VS3HmzpiE7ZVwLQtkt+0d9W43LQMzz4HBnnqvVxKg6O+04d" crossorigin="anonymous">
    <!-- Police pour le titre -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@500&display=swap" rel="stylesheet">
    <!-- Police pour le texte -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2? family=Montserrat:ital,wght@1,200&family=Roboto:wght@500&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
      <h5 class="my-0 font-weight-normal mr-auto" style="font-family: 'Montserrat', sans-serif;">The Hatching "Hacking Cercle"</h5>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent" style="font-family: 'Montserrat', sans-serif;">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="/team">Team <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/contact">Contact</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/">Accueil</a>
            </li>
          </ul>
        </div>
      </nav>
    </div>

    <%= yield %>
    <!-- Optional JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous"></script>
  </body>
</html>

app/views/users/show.html.erb
<h1>Voici la page profil de l'auteur de potins n°<%= @user_hash['index'] %></h1>
<div>
  <% if !@user_hash['user'].nil? %>
    <p>Son prénom : <%= @user_hash['user'].first_name %></p>
    <p>Son nom : <%= @user_hash['user'].last_name %></p>
    <p>Son email : <%= @user_hash['user'].email %></p>
    <p>Son age : <%= @user_hash['user'].age %></p>
    <p>Sa ville : <%= @user_hash['user'].city.name %> (<%= @user_hash['user'].city.zip_code %>)</p>
  <% else %>
    <p>Aucun utilisateur de n°<%= @user_hash['index'] %> n'existe dans la base!</p>
  <% end %>
</div>

app/views/welcome/show.html.erb
<h1>Bienvenue <%= params[:first_name] %>!</h1>
<h2>Ici c'est notre super site de potins, il est chouette, non ?</h2>